# Generated by Django 4.1.7 on 2023-03-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_image',
        ),
    ]
