# Generated by Django 4.1.7 on 2023-04-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0002_remove_video_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='static/videos/'),
        ),
    ]
