# Generated by Django 4.1.7 on 2023-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
