# Generated by Django 4.1.7 on 2023-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumb_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
