# Generated by Django 4.1.7 on 2023-04-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0005_video_thumb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumb_image',
            field=models.ImageField(null=True, upload_to='static/thumb_img'),
        ),
    ]
