# Generated by Django 4.1.7 on 2023-04-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0008_alter_userreg_email_alter_userreg_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logemail', models.CharField(max_length=100, null=True)),
                ('logpassword', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
