# Generated by Django 4.1.7 on 2023-04-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0009_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='type',
            field=models.CharField(default='user', max_length=100, null=True),
        ),
    ]
