# Generated by Django 4.1.7 on 2023-04-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0010_userlog_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
