# Generated by Django 4.1.7 on 2023-04-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0012_video_liked_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
