# Generated by Django 4.1.7 on 2023-05-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0014_recentupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='image',
            field=models.ImageField(null=True, upload_to='static/profile'),
        ),
    ]
