# Generated by Django 4.1.7 on 2023-05-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0016_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
