# Generated by Django 4.1.7 on 2023-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0018_alter_userreg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='image',
            field=models.ImageField(null=True, upload_to='static/videos/profile/'),
        ),
    ]
