# Generated by Django 4.1.7 on 2023-05-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0019_alter_userreg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='image',
        ),
    ]
