# Generated by Django 4.1.7 on 2023-05-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0022_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
    ]
