# Generated by Django 4.1.7 on 2023-05-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0023_alter_contactus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='created_at',
        ),
    ]
