# Generated by Django 4.1.7 on 2023-05-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0024_remove_contactus_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='suggestion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
