# Generated by Django 4.1.7 on 2023-05-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0025_alter_contactus_email_alter_contactus_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
        migrations.DeleteModel(
            name='UserReg',
        ),
    ]
