# Generated by Django 4.1.7 on 2023-05-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0026_delete_userlog_delete_userreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
