# Generated by Django 4.1.7 on 2023-05-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0028_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='fav',
            field=models.ManyToManyField(to='streamapp.video'),
        ),
    ]
