# Generated by Django 4.1.7 on 2023-05-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0029_userlog_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='fav',
            new_name='favorites',
        ),
    ]
