# Generated by Django 4.1.7 on 2023-05-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0031_remove_userlog_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
