# Generated by Django 4.1.7 on 2023-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0032_delete_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='type',
            field=models.CharField(default='user', max_length=100, null=True),
        ),
    ]
