# Generated by Django 4.1.7 on 2023-05-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0034_userlog_remove_userreg_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
