# Generated by Django 4.1.7 on 2023-05-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0035_delete_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fav',
            field=models.ManyToManyField(related_name='favorite_videos', to='streamapp.userreg'),
        ),
    ]
