# Generated by Django 4.1.7 on 2023-05-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0036_video_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='favorite_videos', to='streamapp.userreg'),
        ),
    ]
