# Generated by Django 4.1.7 on 2023-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0038_alter_video_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='streamapp.userreg'),
        ),
    ]
