# Generated by Django 4.1.7 on 2023-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0040_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='image',
            field=models.ImageField(blank=True, upload_to='profileimages/'),
        ),
    ]
