# Generated by Django 4.1.7 on 2023-05-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0041_userreg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='image',
        ),
        migrations.AddField(
            model_name='userreg',
            name='profileimage',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
