# Generated by Django 4.1.7 on 2023-05-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0042_remove_userreg_image_userreg_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='fav',
            new_name='favorite',
        ),
    ]
