# Generated by Django 4.1.7 on 2023-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0043_rename_fav_video_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_videos', to='streamapp.userreg'),
        ),
    ]
