# Generated by Django 4.1.7 on 2023-05-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0047_remove_comment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumb_image',
            field=models.ImageField(null=True, upload_to='thumb_img/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
