# Generated by Django 4.1.7 on 2023-05-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0048_alter_video_thumb_image_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='cat/'),
        ),
    ]
