# Generated by Django 4.1.7 on 2023-05-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0049_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images_home/')),
            ],
        ),
    ]
