# Generated by Django 4.1.7 on 2023-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0050_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
